[default]
TOKEN_ALGORITHM = 'HS256'
TOKEN_EXPIRE_MINUTES = 60
MONGODB_DATABASE = "duffDB"
MONGODB_CONFIG = { "user" = "duff-api", "password" = "123456", "host" = "127.0.0.1", "port" = "27017" }
EMOJIS = ['🍩', '🍺', '🍫', '🧁', '🍪', '🥨', '🍰', '🥯', '🍮', '🍭', '🍬', '🍯', '🥧', '🍦', '🥓']

[prod]
EMOJIS = ['📺', '🛋️', '🍟', '🚔', '⛪', '🏭', '🎳']
